--CRIA E POPULA TABELA TESTE 

USE curso;

--DROP TABLE ##DADOS

  CREATE TABLE ##DADOS
  (
    NUMERO INT NULL,
	NOME  VARCHAR(20),
  );

  INSERT INTO ##DADOS VALUES (1,'Jack')
  INSERT INTO ##DADOS VALUES (2,'Peter')
  INSERT INTO ##DADOS VALUES (3,'Sam')
  INSERT INTO ##DADOS VALUES (4,'Malcon')
  INSERT INTO ##DADOS VALUES (5,'David')
  INSERT INTO ##DADOS VALUES (6,'Marlos')
  INSERT INTO ##DADOS VALUES (7,'Greg')
  INSERT INTO ##DADOS VALUES (8,'Jorge')
  INSERT INTO ##DADOS VALUES (9,'Richard')
  INSERT INTO ##DADOS VALUES (10,'Anne')

--SELECT * FROM ##DADOS
--DECLARANDO CURSOR
  DECLARE cDados SCROLL CURSOR FOR 
  SELECT NUMERO, NOME FROM ##DADOS

OPEN cDados;

--VERIFICA A QUANTIDADE DE LINHAS 
  SELECT @@CURSOR_ROWS;

--PRIMEIRO REGISTRO DO CURSOR 
  FETCH ABSOLUTE 1 FROM cDados;

--PROXIMO REGISTRO
  FETCH NEXT FROM cDados;
  
--ULTIMO REGISTRO
  FETCH LAST FROM cDados;

--RETORNA A LINHA  ANTERIOR AO REGISTRO ATUAL DO CURSOR 
  FETCH PRIOR FROM cDados;

--VOLTA PARA A SEGUNDA LINHA DO CURSOR
  FETCH ABSOLUTE 2 FROM cDados;

--AVANÇA TRES REGISTROS EM RELAÇÃO AO REGISTRO ATUAL
  FETCH RELATIVE 3 FROM cDados;

--RETROCEDE DOIS REGISTROS EM RELAÇÃO AO REGITRO ATUAL
  FETCH RELATIVE -2 FROM cDados;

CLOSE cDados;
DEALLOCATE cDados;



