--FUNÇÕES DATA E HORA DO SISTEMA
  
  SELECT SYSDATETIME() ExSYSDATETIME
  SELECT SYSDATETIMEOFFSET() ExSYSDATETIMEOFFSET
  SELECT SYSUTCDATETIME() ExSYSUTCDATETIME
  SELECT CURRENT_TIMESTAMP ExCURRENT_TIMESTAMP 
  SELECT GETDATE() ExGETDATE
  SELECT GETUTCDATE() ExGETUTCDATE




