

--USE MASTER 
--DROP DATABASE DB_LGPD

  CREATE DATABASE DB_LGPD;
  GO

  USE DB_LGPD
  GO

  CREATE TABLE CLIENTE 
   (ID_CLIENTE       INT IDENTITY PRIMARY KEY,
    PRIMEIRO_NOME    VARCHAR(100)MASKED WITH (FUNCTION ='PARTIAL(1,"XXXXXXX",0)')NOT NULL,
	ULTIMO_NOME      VARCHAR(100)NOT NULL,
	TELEFONE         VARCHAR(12)MASKED WITH (FUNCTION = 'DEFAULT()')NULL,
	EMAIL            VARCHAR(100)MASKED WITH(FUNCTION = 'EMAIL()')NULL,
	CARTAO_CREDITO   VARCHAR(20)NOT NULL,
	SALARIO          DECIMAL(10,2)NOT NULL)  ;

  INSERT CLIENTE VALUES
  ('ANDRE','ROSA','555.123.4567','ANDRE@TESTE.COM','1111-2222-3333-4444',12000),
  ('PEDRO','SILVA','555.123.4568','PEDRO@TESTE.COM','1234-4321-9632-7411',9000),
  ('MARIANA','SOUZA','555.123.4569','MARIANA@TESTE.COM','1234-4321-9632-7411',15000);
  

--DADOS TESTE
  SELECT * FROM CLIENTE 


--CRIA ROLE PERSONALIZADAS PARA ACESSO
  CREATE ROLE VENDEDORES_COM_ACESSO
  CREATE ROLE VENDEDORES_SEM_MASK
  CREATE ROLE VENDEDORES_SEM_ACESSO

--CRIA USERS TESTE

  CREATE USER JOAO WITHOUT LOGIN;
  CREATE USER PEDRO WITHOUT LOGIN;
  CREATE USER PAULO WITHOUT LOGIN;


--ADICIONA USERS AS RESPECTIVAS ROLES

--ADICIONA USUARIO A ROLE VENDEDORES_COM_ACESSO
  EXEC sp_addrolemember 'VENDEDORES_COM_ACESSO','JOAO';
  EXEC sp_addrolemember 'VENDEDORES_COM_ACESSO','PEDRO';

--ADICIONA USUARIO A ROLE VENDEDORES_SEM_MASK
  EXEC sp_addrolemember 'VENDEDORES_SEM_MASK','PEDRO';

--ADICIONA USUARIO A ROLE VENDEDORES_SEM_ACESSO
  EXEC sp_addrolemember 'VENDEDORES_SEM_ACESSO','PAULO';

--CONCEDE ACESSO A ROLE DE LEITURA

  GRANT SELECT ON CLIENTE TO VENDEDORES_COM_ACESSO

--CONCEDE ACESSO A ROLE DE LEITURA SEM MASCARA
  
  GRANT UNMASK TO VENDEDORES_SEM_MASK;

--NEGA ACESSO A ROLE 

  DENY SELECT ON CLIENTE TO VENDEDORES_SEM_ACESSO 


--TESTE DE ACESSO JOAO
  EXECUTE AS USER = 'JOAO';
  SELECT * FROM CLIENTE ;
  REVERT;
  

--TESTE DE ACESSO PEDRO

  EXECUTE AS USER = 'PEDRO';
  SELECT * FROM CLIENTE;
  REVERT;

--TESTE DE ACESSO PAULO --SEM ACESSO, ERRO ESPERADO
  
  EXECUTE AS USER = 'PAULO';
  SELECT * FROM CLIENTE;
  REVERT;


--IDENTIFICANDO OS CAMPOS COM MASCARA
  SELECT C.NAME, TBL.NAME AS TABLE_NAME, C.IS_MASKED, C.MASKING_FUNCTION
  FROM SYS.masked_columns AS C
  JOIN SYS.TABLES AS TBL
  ON C.[object_id] = TBL.[object_id]
  WHERE IS_MASKED = 1;


--ADICIONAR MASCARA NA TABELA EXISTENTE 

--MASCARA ULTIMO NOME 
  ALTER TABLE CLIENTE ALTER COLUMN ULTIMO_NOME ADD MASKED WITH (FUNCTION = 'PARTIAL(2,"XXXXXXX",0)')

--MASCARA TELEFONE
  ALTER TABLE CLIENTE ALTER COLUMN TELEFONE ADD MASKED WITH (FUNCTION = 'PARTIAL(5,"XXXXXXX",0)')

--MASCARA CARTÃO DE CREDITO
  ALTER TABLE CLIENTE ALTER COLUMN CARTAO_CREDITO ADD MASKED WITH (FUNCTION = 'PARTIAL(0,"XXXX-XXXX-XXXX",4)')

--MASCARA SALARIO
  ALTER TABLE CLIENTE ALTER COLUMN SALARIO ADD MASKED WITH (FUNCTION = 'DEFAULT()')

--TESTE DE ACESSO JOAO
  
  EXECUTE AS USER = 'JOAO';
  SELECT * FROM CLIENTE;
  REVERT;

--TESTE DE ACESSO PEDRO

  EXECUTE AS USER = 'PEDRO';
  SELECT * FROM CLIENTE;
  REVERT;

--TESTE DE ACESSO PAULO --SEM ACESSO, ERRO ESPERADO
  
  EXECUTE AS USER = 'PAULO';
  SELECT * FROM CLIENTE;
  REVERT; 


--REMOVER USERS DE ROLE 

  EXEC sp_droprolemember 'VENDEDORES_SEM_MASK', 'PEDRO';


--TESTE DE ACESSO PEDRO

  EXECUTE AS USER = 'PEDRO';
  SELECT * FROM CLIENTE;
  REVERT;