/*

  DROP TABLE T_FUNCIONARIO
  DROP TABLE T_DEPTOS
  DROP TABLE T_FUNC_SAL
  DROP TABLE T_BONUS
  DROP FUNCTION dbo.FUNC_CALC_BONUS


*/

USE CURSO
GO

  CREATE TABLE T_FUNCIONARIO
   (
     ID_FUNC INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	 NOME_FUNC VARCHAR(30) NOT NULL,
	 ID_DEPTO INT NOT NULL
     
	 )

  GO

  CREATE TABLE T_DEPTOS
   (
     ID_DEPTO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	 NOME_DEPTO VARCHAR(30)
	 )
  GO

  CREATE TABLE T_FUNC_SAL
   (
     ID_FUNC INT NOT NULL PRIMARY KEY,
	 VALOR DECIMAL(10,2) NOT NULL
	 )
  GO 

  CREATE TABLE T_BONUS
   (
     ID_FUNC  INT NOT NULL PRIMARY KEY,
	 PCT_BONUS DECIMAL(10,2) NOT NULL
     )
  GO



--POPULANDO TABELAS
  INSERT INTO T_DEPTOS
  VALUES  ('ADMINISTRACAO'),
          ('PRODUCAO')

  INSERT INTO T_FUNCIONARIO
  VALUES  ('WILL',1), ('JOHN',1),
          ('PETER',1),('DEREK',2),
		  ('GREG',2),('MARY',2),
		  ('JANE',1),('MARK',2),
		  ('SAMY',1),('SAUL',2)
  
  INSERT INTO T_FUNC_SAL
  VALUES   (1,1000),(2,1500),
           (3,3000),(4,3500),
		   (5,4000),(6,4500),
		   (7,1250),(8,1750),
		   (9,2250),(10,3250)

  INSERT INTO T_BONUS
  VALUES (1,2),(3,2.5),
        (5,1.75),(7,2.75),
		(9,1.25)

--VERIFICANDO DADOS
  SELECT * FROM T_FUNCIONARIO;
  SELECT * FROM T_DEPTOS;
  SELECT * FROM T_FUNC_SAL;
  SELECT * FROM T_BONUS;


--DEMONSTRANDO  INNER , LEFT JOIN, LEFT OUTER JOIN
  SELECT A.ID_FUNC,
         A.NOME_FUNC,
		 B.PCT_BONUS
  FROM   T_FUNCIONARIO A
         INNER JOIN T_BONUS B
		        ON A.ID_FUNC = B.ID_FUNC

--CRIANDO A FUNÇÃO DE CALCULA BONUS 
  CREATE FUNCTION DBO.FUNC_CALC_BONUS (@P_ID_FUNC INT)
  RETURNS @TBL TABLE (
     VAL_BONUS DECIMAL(10,2)
	                 )
  AS 
  BEGIN
   --TABELA ALVO
     INSERT INTO @TBL
   --SELECT PARA INSERT
     SELECT
	    CAST(A.VALOR * (B.PCT_BONUS / 100) AS DECIMAL (10,2)) AS VAL_BONUS
     FROM T_FUNC_SAL A 
	 INNER JOIN T_BONUS  B
	 ON A.ID_FUNC = B.ID_FUNC
	 WHERE A.ID_FUNC= @P_ID_FUNC
	 RETURN
  END;

--INVOCANDO A FUNÇÃO
  SELECT * FROM DBO.FUNC_CALC_BONUS(1)   

--USANDO CROSS APPLY
  SELECT        A.ID_FUNC,
                A.NOME_FUNC,
		        C.NOME_DEPTO,
		        B.VALOR,
		        F_BON.VAL_BONUS
  FROM          T_FUNCIONARIO A
  INNER JOIN    T_FUNC_SAL B
  ON            A.ID_FUNC = B.ID_FUNC
  INNER JOIN    T_DEPTOS C
  ON            A.ID_DEPTO = C.ID_DEPTO
  CROSS APPLY   DBO.FUNC_CALC_BONUS (A.ID_FUNC) AS F_BON;

--USANDO OUTER APPLY
  SELECT        A.ID_FUNC,
                A.NOME_FUNC,
			    C.NOME_DEPTO,
                B.VALOR,
		        ISNULL(F_BON.VAL_BONUS,0) VAL_BONUS
  FROM          T_FUNCIONARIO A
  INNER JOIN    T_FUNC_SAL B
  ON            A.ID_FUNC = B.ID_FUNC
  INNER JOIN    T_DEPTOS C
  ON            A.ID_DEPTO = C.ID_DEPTO
  OUTER APPLY   DBO.FUNC_CALC_BONUS (A.ID_FUNC) AS F_BON;


