

--DROP TABLE CAD_PESSOA;

USE curso
CREATE TABLE CAD_PESSOA
(
  ID_PESSOA INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(50),
  EMAIL VARCHAR(30),
  SITUACAO CHAR (1),
  CONSTRAINT CK_SITUA CHECK(SITUACAO IN ('B','A'))	
);
 
 --DROP PROCEDURE SP_CRUD
  CREATE PROCEDURE SP_CRUD     @V_OPER        CHAR(1),      --I INSERIR --A ATUALIZA --S SELECIONA --D DELETE 
                               @V_ID_PESSOA   INTEGER,      --CODIGO DA PESSOA 
							   @V_NOME        VARCHAR(50),  --
							   @V_EMAIL       VARCHAR(30),
							   @V_SITUACAO	CHAR(1)
  AS 
  BEGIN 
--DECLARANDO VARIAVEIS
  DECLARE 
    @V_SID_PESSOA INTEGER,
	@V_SNOME      VARCHAR(50),
	@V_SEMAIL     VARCHAR(30),
	@V_SSITUACAO  CHAR(1);

BEGIN TRANSACTION

--VERIFICA OPERAÇAO DE INSERT
  
  IF(@V_OPER='I')
  BEGIN 
    IF (@V_ID_PESSOA IS NULL OR @V_ID_PESSOA=''
	    OR @V_NOME IS NULL OR @V_NOME=''
	    OR @V_EMAIL IS NULL OR @V_EMAIL='')
		BEGIN 
		     ROLLBACK;
			 PRINT 'CAMPOS IMCOMPLETOS';
			 GOTO FIM_ERRO
        END
		ELSE 
		    INSERT INTO CAD_PESSOA(ID_PESSOA, NOME , EMAIL, SITUACAO) VALUES (@V_ID_PESSOA, @V_NOME, @V_EMAIL,'A');
			GOTO FIM_CERTO
        END
  END

--VERIFICA OPERAÇÃO DE ATUALIZAÇÃO 
  
  IF (@V_OPER='A')	 
     BEGIN 
	     IF (@V_ID_PESSOA IS NULL OR @V_ID_PESSOA='')
		   BEGIN 
		     ROLLBACK;
			 PRINT 'CAMPOS IMCOMPLETOS';
			 GOTO FIM_ERRO
           END
	   ELSE    
	       UPDATE CAD_PESSOA SET NOME =ISNULL (@V_NOME, NOME), EMAIL=ISNULL(@V_EMAIL, EMAIL),
		   SITUACAO=ISNULL(@V_SITUACAO,SITUACAO)
		   WHERE ID_PESSOA = @V_ID_PESSOA;
		   GOTO FIM_CERTO
     END 

--VERIFICAÇÃO OPERÇÃO DE DELETE 
  IF(@V_OPER='D') BEGIN 
  IF(@V_ID_PESSOA IS NULL OR @V_ID_PESSOA='')
    BEGIN
	  ROLLBACK;
	  PRINT 'CAMPOS IMCOMPLETOS';
	  GOTO FIM_ERRO
    END
	ELSE 
	     DELETE FROM CAD_PESSOA WHERE ID_PESSOA = @V_ID_PESSOA;
		   GOTO FIM_CERTO	
  END

--VERIFICA OPERAÇÃO DE SELECT 
  IF(@V_OPER='S')
    BEGIN

    SELECT	@V_SID_PESSOA=a.id_pessoa,@V_SNOME=a.nome,@V_SEMAIL=EMAIL,@V_SSITUACAO=SITUACAO
	FROM CAD_PESSOA a
	WHERE ID_PESSOA = @V_ID_PESSOA;
	  
	     PRINT CONCAT('ID: ', @V_SID_PESSOA);
		 PRINT 'Nome: ' +@V_SNOME;
		 PRINT 'E-mail: ' +@V_SEMAIL;
		 PRINT 'Situação: ' +@V_SSITUACAO;

		 GOTO FIM_CERTO

    END

  FIM_CERTO:
  COMMIT;
  PRINT 'DADOS SELECIONADOS, INSERIDOS OU ATUALIZADO COM SUCESSO';
  GOTO FIM

  FIM_ERRO:
  PRINT 'ALGO DEU ERRADO!!!'; 

  FIM:
  PRINT 'FINALIZADO!!';


--INSERT
  EXECUTE SP_CRUD 'I',1,'JONHY','JONHY@JONHY.COM','A';
  EXECUTE SP_CRUD 'I',2,'PETER','PETER@PETER.COM','A';
  EXECUTE SP_CRUD 'I',3,'DEREK','DEREK@DEREK.COM','A';
  EXECUTE SP_CRUD 'I',5,NULL,'JP@JP.COM','A';

  SELECT * FROM CAD_PESSOA


--SELECT
  EXECUTE SP_CRUD @V_OPER='S',@V_ID_PESSOA=2,@V_NOME=NULL,@V_EMAIL=NULL,@V_SITUACAO=NULL; 

--UPDATE
  EXECUTE SP_CRUD @V_OPER='A',@V_ID_PESSOA=2,@V_NOME='PETER',@V_EMAIL='PETE@PETER.COM',@V_SITUACAO='A'; 

--DELETE
 EXECUTE SP_CRUD @V_OPER='D',@V_ID_PESSOA=2,@V_NOME=NULL,@V_EMAIL=NULL,@V_SITUACAO=NULL; 


