USE curso;

--DROP TABLE FUNC

  CREATE TABLE FUNC(
  MATRICULA INT IDENTITY(1,1) PRIMARY KEY,
  NOME      VARCHAR(30) NOT NULL,
  SOBRENOME VARCHAR(30) NOT NULL,
  ENDERECO  VARCHAR(30) NOT NULL,
  CIDADE    VARCHAR(30) NOT NULL,
  ESTADO    VARCHAR(2) NOT NULL,
  DATA_NASC DATETIME
  );

  INSERT INTO FUNC VALUES ('Steve','Morse','Rua 13','JUNDIAI','SP','1977-11-05');
  INSERT INTO FUNC VALUES ('Joao','Pedro','Rua 14','SÃO PAULO','SP','1980-02-10');
  INSERT INTO FUNC VALUES ('Maria','Clara','Rua 15','RIBEIRÃO PRETO','SP','1985-05-05');
  INSERT INTO FUNC VALUES ('Pedro','Luiz','Rua 16','Campinas','SP','1990-12-09');

--SELECT * FROM FUNC
--DROP TABLE auditoria_salario

  CREATE TABLE auditoria_salario (
  matricula   VARCHAR(30)   NOT NULL,
  sal_antes   DECIMAL(10,2) NOT NULL,
  sal_depois  DECIMAL(10,2) NOT NULL,
  usuario     VARCHAR(20)   NOT NULL,
  data_atualizacao DATETIME NOT NULL
  );

--DROP TABLE SALARIO
  CREATE TABLE SALARIO (
  matricula INT NOT NULL,
  SALARIO   DECIMAL(10,2) NOT NULL
  );

  INSERT INTO SALARIO VALUES (1,1000)
  INSERT INTO SALARIO VALUES (2,1500)
  INSERT INTO SALARIO VALUES (3,2000)
  INSERT INTO SALARIO VALUES (4,2500)












