--PROCEDURE GERA PEDIDO DE COMPRAS
--PROCEDURE PARA CRIAR PEDIDO DE COMPRAS COM BASE NECESSIDADES  DA ORDEM DE PRODUÇAO
--PARAMETROS @EMPRESA,@MES,@ANO
--TABELAS ORIGEM ORDEM_PROD
--TABELAS NECESSARIAS,FICHA_TECNICA,MATERIAL,FORNECEDORES 
--TABELAS DESTINO PED_COMPRAS,PED_COMPRAS_ITENS
--TABELAS ATUALIZADAS ORDEM_PROD SITUACAO DE A ABERTA PARA P PLANEJ
--DROP PROCEDURE PROC_GER_PED_COMPRAS
--EXEC PROD_GER_PED_COMPRAS 1,05,2017
--DROP PROCEDURE PROC_GER_PED_COMPRAS
--FASE 1 PEDIDO DE VENDA
--FASE 2 ORDEM DE PRODUÇAO
--FASE 3 PEDIDO DE COMPRAS >> ESTAMOS AQUI
--CORREÇAO DE CARGA -- FORAM CARREGADOS MATERIAIS COM ID FOR 3 QUE PERTENCE  A EMPRESA 2

  USE MINIERP_MULT
  GO
  UPDATE MATERIAL SET ID_FORNEC=1 WHERE COD_EMPRESA=1 AND COD_MAT IN (9,10);

--ALTER TABLE TABELAS
  ALTER TABLE PED_COMPRAS_ITENS ALTER COLUMN QTD DECIMAL(10,2)
  ALTER TABLE PED_VENDAS_ITENS  ALTER COLUMN QTD DECIMAL(10,2)
--SELECT * FROM MATERIAL
--CRIANDO PROCEDURE 
--DROP PROCEDURE PROC_GER_PED_COMPRAS
  CREATE PROCEDURE PROC_GER_PED_COMPRAS (@COD_EMPRESA INT,
                                        @MES VARCHAR(2),
										@ANO VARCHAR(4))
  AS
    BEGIN
  --DECLARANDO TABLE TEMP
  --VARIAVEL DE TABELA PARA ATRIBUIR SAIDA OUTPUT
  DECLARE @PED_AUX TABLE
  (
       NUM_PEDIDO_AUX INT 
   )

   DECLARE @RETORNO TABLE 
   (
    RET_ORD INT,
	RET_SIT VARCHAR(1)
   )

--DECLARANDO VARIAVEIS

DECLARE @COD_EMPRESA_AUX  INT,
        @MES_AUX          VARCHAR(2),
		@ANO_AUX          VARCHAR(4),
		@NUM_PEDIDO       INT,
		@ID_ORDEM         INT,
		@NUM_PEDIDO_AUX   INT,
		@COD_MAT          INT,
		@ID_FORNEC        INT,
		@COD_PAGTO        INT,
		@DATA_PEDIDO      DATE,
		@DATA_ENTREGA     DATE,
		@SITUACAO         VARCHAR(1),
		@QTD              DECIMAL(10,2),
		@PRECO_UNIT       DECIMAL(10,2),
		@CONT_SEQ         INT,
		@TOTAL_PED        DECIMAL(10,2),
		@ERRO_INTERNO    INT 

SET @TOTAL_PED = 0;
--INICIA A TRANSAÇAO
  BEGIN TRANSACTION
--INICIA BEGIN TRY
  BEGIN TRY
--CONDIÇAO PARA GERAL O PEDIDO MES RETROATIVOS
  IF (@MES='1')
    BEGIN
	     SET @MES_AUX=12;
		 SET @ANO_AUX=@ANO-1;
	END
	    ELSE
	BEGIN
	  SET @MES_AUX=@MES-1;
	  SET @ANO_AUX=@ANO;
	END
--VERIFICANDO SE EXISTEM ORDEM  PARA PLANEJ STATUS ABERTO
  SELECT A.COD_EMPRESA,A.ID_ORDEM FROM ORDEM_PROD A
         WHERE A.COD_EMPRESA=@COD_EMPRESA
		 AND MONTH(A.DATA_INI)=@MES
		 AND YEAR (A.DATA_INI)=@ANO
		 AND A.SITUACAO='A'

    IF @@ROWCOUNT=0
	BEGIN
        SET @ERRO_INTERNO=1
	END
	ELSE
	BEGIN

  --ATRIBUINDO VALORES
    SET @CONT_SEQ=1
  --SET @NUM_PEDIDO=0
  --SET @NUM_PEDIDO_AUX=0;


--CURSOR PARA GRAVAR CABEÇALHO PEDIDO DE COMPRAS
--SELECT  PARA GERAR NECESSIDADES
--select * from ped_vendas
























   