--CRIACAO TRIGGER AUDITA SALARIO
--DROP TRIGGER TG_AUDIT_SAL
--TRIGGER PARA AUDITAR ALTERACOES DE SALARIO

  USE MINIERP_MULT
  GO
  
  CREATE TRIGGER TG_AUDIT_SAL
  ON SALARIO
  AFTER UPDATE
  AS 
    BEGIN
	    DECLARE @COD_EMPRESA INT
		DECLARE @MATRICULA_AUX INT

	   IF UPDATE (SALARIO) --SE ATUALIZAR CAMPO SALARIO TABELA SALARIO
	   BEGIN
	   DECLARE CURSOR_AUDITORIA CURSOR FOR
	    

		SELECT COD_EMPRESA,MATRICULA FROM  INSERTED /* TABELA VIRTUAL INSERT */

		OPEN CURSOR_AUDITORIA

		FETCH NEXT FROM CURSOR_AUDITORIA INTO @COD_EMPRESA,@MATRICULA_AUX

		WHILE @@FETCH_STATUS = 0
		  BEGIN
		     INSERT INTO AUDITORIA_SALARIO
			 SELECT      I.COD_EMPRESA,
			             I.MATRICULA,
						 D.SALARIO,
						 I.SALARIO,
						 SYSTEM_USER,
						 GETDATE()
             FROM DELETED D,
			      INSERTED I
			 WHERE D.COD_EMPRESA=@COD_EMPRESA
			       AND D.COD_EMPRESA=I.COD_EMPRESA
				   AND D.MATRICULA=I.MATRICULA
				   AND @MATRICULA_AUX=I.MATRICULA

             FETCH NEXT FROM CURSOR_AUDITORIA
			 INTO @COD_EMPRESA,@MATRICULA_AUX

          END
        CLOSE  CURSOR_AUDITORIA
        DEALLOCATE CURSOR_AUDITORIA
	   END
    END


--TESTANDO TRIGGER
  UPDATE SALARIO SET SALARIO=SALARIO*1.10	
  WHERE COD_EMPRESA =1
  AND MATRICULA IN (3,4)

--VERIFICANDO
  SELECT * FROM AUDITORIA_SALARIO
  WHERE COD_EMPRESA =1
  AND MATRICULA IN (3,4)
