--DROP TRIGGER TG_BLOQUEIA_USUARIO
  
  CREATE TRIGGER TG_BLOQUEIA_USUARIO ON FUNCIONARIO
  AFTER UPDATE
  AS 
  BEGIN
      DECLARE @COD_EMPRESA INT
	  DECLARE @MATRICULA INT 
	  DECLARE @DATA_DEMISS DATE

	  SELECT @COD_EMPRESA=I.COD_EMPRESA,
	         @MATRICULA=I.MATRICULA,
			 @DATA_DEMISS=I.DATA_DEMISS
      FROM INSERTED I;

    IF UPDATE (DATA_DEMISS) AND @DATA_DEMISS<>'1990-01-01'
	  BEGIN
	      UPDATE USUARIO SET SITUACAO ='B' --BLOQUEIA
		  WHERE COD_EMPRESA=@COD_EMPRESA
		  AND MATRICULA=@MATRICULA;
		  PRINT 'BLOQUEIO DA MATRICULA ' + CAST(@MATRICULA AS VARCHAR(20))+' REALIZADO COM SUCESSO';
      END
  END

  UPDATE FUNCIONARIO SET DATA_DEMISS=GETDATE()
  WHERE COD_EMPRESA=1
  AND MATRICULA='4'

  --SELECT * FROM USUARIO ORDER BY COD_EMPRESA,MATRICULA
  --SELECT * FROM FUNCIONARIO ORDER BY COD_EMPRESA,MATRICULA