--V_FUNCIONAIRO
--TABELAS FUNCIONARIO,CARGOS, CENTRO_CUSTO
--SELECT * FROM V_FUNCIONARIO
USE MINIERP_MULT
GO

  CREATE VIEW V_FUNCIONARIO
  AS 
     SELECT A.COD_EMPRESA,
	        A.MATRICULA,
			A.COD_CC,
			C.NOME_CC,
			A.NOME,
			A.COD_CARGO,
			B.NOME_CARGO,
			A.DATA_ADMISS,
			A.DATA_DEMISS,
			
			CASE WHEN A.DATA_DEMISS='1900-01-01' THEN 'ATIVO'
			       ELSE 'DESLIGADO' END SITUACAO
	 FROM
	 FUNCIONARIO A
	 INNER JOIN CARGOS B
	 ON A.COD_EMPRESA=B.COD_EMPRESA
	 AND A.COD_CARGO=B.COD_CARGO
	 INNER JOIN CENTRO_CUSTO C
	 ON A.COD_CC=C.COD_CC
	 AND A.COD_EMPRESA=C.COD_EMPRESA

--TESTANDO VIEW
  SELECT * FROM V_FUNCIONARIO

--V_FATURAMENTO
--NOTA_FISCAL, NOTA_FISCAL_ITENS,MATERIAL,CLIENTES,CIDADES
--SELECT * FROM MATERIAL
--SELECT * FROM CLIENTES
--SELECT * FROM CIDADES

  CREATE VIEW V_FATURAMENTO
  AS 
  SELECT  A.COD_EMPRESA,
		  A.NUM_NF,
		  A.ID_CLIFOR,
		  CAST(A.DATA_EMISSAO AS DATE) DATA_EMISSAO,
		  B.COD_MAT,
		  C.DESCRICAO,
		  D.RAZAO_CLIENTE,
		  E.NOME_MUN,
		  B.QTD,
		  B.VAL_UNIT,
		  B.QTD*B.VAL_UNIT TOTAL
  FROM NOTA_FISCAL A
  INNER JOIN NOTA_FICAL_ITENS B
  ON A.COD_EMPRESA=B.COD_EMPRESA
  AND A.NUM_NF=B.NUM_NF 

  INNER JOIN MATERIAL C
  ON A.COD_EMPRESA=C.COD_EMPRESA
  AND B.COD_MAT=C.COD_MAT

  INNER JOIN CLIENTES D
  ON A.COD_EMPRESA=D.COD_EMPRESA
  AND A.ID_CLIFOR=D.ID_CLIENTE

  INNER JOIN CIDADES E
  ON D.COD_CIDADE=E.COD_CIDADE
  WHERE A.TIP_NF='S'


--CRIAMOS INDICE PARA MELHORAR PERFORMANCE
--CREATE INDEX IX_FAT1 ON NOTA_FISCAL(TIP_NF)
--EXEC SP_STATISTICS NOTA _FISCAL



