USE MINIERP_MULT;

--CRIACAO DE TABELAS APONTAMENTOS DE PRODUCAO
--DROP TABLE APONTAMENTOS 
  CREATE TABLE APONTAMENTOS
   (
    COD_EMPRESA   INT                NOT NULL,
	ID_APON       INT IDENTITY(1,1)  NOT NULL,
	ID_ORDEM      INT                NOT NULL,
	COD_MAT_PROD  INT,
	QTD_APON      DECIMAL(10,2),
	DATA_APON     DATETIME           NOT NULL,
    --CAMPO LOTE CRIADO NO FINAL
	--LOGIN, SERA CRIADO APOS CRIACAO DA TABELA USUARIOS 
	CONSTRAINT  FK_APON1 FOREIGN KEY (COD_EMPRESA, COD_MAT_PROD)
	REFERENCES	MATERIAL (COD_EMPRESA, COD_MAT),
	CONSTRAINT  FK_APON2 FOREIGN KEY (COD_EMPRESA,ID_ORDEM)
	REFERENCES  ORDEM_PROD (COD_EMPRESA,ID_ORDEM),
	CONSTRAINT  PK_APON1 PRIMARY KEY (COD_EMPRESA,ID_APON)
    );

--CRIACAO DA TABELA FICHA TECNICA
  CREATE TABLE FICHA_TECNICA
   (
     COD_EMPRESA    INT            NOT NULL,
	 ID_REF         INT IDENTITY   NOT NULL PRIMARY KEY,
	 COD_MAT_PROD   INT            NOT NULL,
	 COD_MAT_NECES  INT            NOT NULL,
	 QTD_NECES      DECIMAL(10,2)  NOT NULL,
	 CONSTRAINT  FK_FIC1 FOREIGN KEY (COD_EMPRESA, COD_MAT_PROD)
	 REFERENCES	 MATERIAL (COD_EMPRESA, COD_MAT),
	 CONSTRAINT  FK_FIC2 FOREIGN KEY (COD_EMPRESA,COD_MAT_NECES)
	 REFERENCES  MATERIAL (COD_EMPRESA,COD_MAT)
	 );

--CRIACAO DA TABELA CONSUMO
--DROP TABLE CONSUMO
  CREATE TABLE CONSUMO 
  (
   COD_EMPRESA    INT            NOT NULL,
   ID_APON        INT            NOT NULL, 
   COD_MAT_NECES  INT            NOT NULL,
   QTD_CONSUMIDA  DECIMAL(10,2)  NOT NULL,
   LOTE           VARCHAR (20)   NOT NULL,
   CONSTRAINT  FK_CONS1 FOREIGN KEY (COD_EMPRESA, COD_MAT_NECES)
   REFERENCES  MATERIAL (COD_EMPRESA, COD_MAT),
   CONSTRAINT  FK_CONS2 FOREIGN KEY (COD_EMPRESA,ID_APON)
   REFERENCES  APONTAMENTOS (COD_EMPRESA,ID_APON)
   );

--SUPRIMENTOS
--CRIACAO DA TABELA 
  CREATE TABLE ESTOQUE 
  (
   COD_EMPRESA  INT            NOT NULL,
   COD_MAT      INT            NOT NULL,
   QTD_SALDO    DECIMAL(10,2)  NOT NULL,
     CONSTRAINT  FK_EST1 FOREIGN KEY (COD_EMPRESA, COD_MAT)
	 REFERENCES	 MATERIAL (COD_EMPRESA, COD_MAT),
	 CONSTRAINT  PK_EST1 PRIMARY KEY (COD_EMPRESA,COD_MAT)
   );
   
--DROP TABLE ESTOQUE_LOTE 
--CRIA플O TABELAS ESTOQUE_LOTE 
  CREATE TABLE ESTOQUE_LOTE 
    (
	 COD_EMPRESA  INT            NOT NULL,
	 COD_MAT      INT            NOT NULL,
	 LOTE         VARCHAR(20)    NOT NULL,
	 QTD_LOTE     DECIMAL(10,2)  NOT NULL,
	 CONSTRAINT  PK_ESTL1 PRIMARY KEY (COD_EMPRESA, COD_MAT, LOTE),  --PK COMPOSTA
	 CONSTRAINT  FK_ESTL1 FOREIGN KEY (COD_EMPRESA,COD_MAT)
     REFERENCES	 MATERIAL (COD_EMPRESA, COD_MAT) 
	);

--CRIA플O TABELA MOV ESTOQUE
--DROP TABLE ESTOQUE_MOV
  CREATE TABLE ESTOQUE_MOV
   ( 
    COD_EMPRESA    INT                NOT NULL,
	ID_MOV         INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	TIP_MOV        VARCHAR(1), --S = SAIDA, E = ENTRADA
	COD_MAT        INT                NOT NULL,
	LOTE           VARCHAR(20)        NOT NULL,
	QTD            DECIMAL(10,2)      NOT NULL,
	DATA_MOV       DATE               NOT NULL,
	DATA_HORA      DATETIME           NOT NULL,
	CONSTRAINT FK_ESTM1 FOREIGN KEY (COD_EMPRESA,COD_MAT)
	REFERENCES MATERIAL(COD_EMPRESA,COD_MAT)
	--CAMPO LOGIN TABELA ESTOQUE_MOV CRIACAO APOS TABELA USUARIO
	);

--CRIA플O TABELAS PED_COMPRAS
--DROP TABLE PED_COMPRAS

  CREATE TABLE PED_COMPRAS
    (
	 COD_EMPRESA       INT            NOT NULL,
	 NUM_PEDIDO        INT            NOT NULL,
	 ID_FORNEC         INT            NOT NULL,
	 COD_PAGTO         INT            NOT NULL, 
	 --ALTERAR COD_PAGTO TAB PED_COMPRAS PAR FOREIGN KEY APOS TABELA COND_PAGTO
	 DATA_PEDIDO       DATE           NOT NULL,
	 DATA_ENTREGA      DATE           NOT NULL,
	 SITUACAO          NCHAR(1)       NOT NULL,
	 TOTAL_PED         DECIMAL(10,2),
	 CONSTRAINT FK_PEDC1 FOREIGN KEY (COD_EMPRESA, ID_FORNEC)
	 REFERENCES FORNECEDORES (COD_EMPRESA, ID_FORNEC),
	 CONSTRAINT PK_PEDC1 PRIMARY KEY (COD_EMPRESA,NUM_PEDIDO)
      );

--CRIA플O DA TABELA PEDIDO COMPRAS	
  CREATE TABLE PED_COMPRAS_ITENS
    (
	 COD_EMPRESA    INT            NOT NULL,
	 NUM_PEDIDO     INT            NOT NULL,
	 SEQ_MAT        INT            NOT NULL,
	 COD_MAT        INT            NOT NULL,
	 QTD            INT            NOT NULL,
	 VAL_UNIT       DECIMAL(10,2)  NOT NULL,
	 CONSTRAINT PK_PEDCIT1 PRIMARY KEY (COD_EMPRESA, NUM_PEDIDO, SEQ_MAT),
	 CONSTRAINT FK_PEDCIT1 FOREIGN KEY (COD_EMPRESA, NUM_PEDIDO)
	 REFERENCES PED_COMPRAS (COD_EMPRESA, NUM_PEDIDO),
	 CONSTRAINT FK_PEDIT2  FOREIGN KEY (COD_EMPRESA, COD_MAT)
	 REFERENCES MATERIAL    (COD_EMPRESA,COD_MAT)
	 );

--RH
--CRIA플O TABELAS CENTRO DE CUSTO
  CREATE TABLE CENTRO_CUSTO
    (
	 COD_EMPRESA     INT          NOT NULL,
	 COD_CC          VARCHAR(4)   NOT NULL,
	 NOME_CC         VARCHAR(20)  NOT NULL,
	 CONSTRAINT PK_CC1 PRIMARY KEY (COD_EMPRESA, COD_CC),
	 CONSTRAINT FK_CC1 FOREIGN KEY (COD_EMPRESA)
	 REFERENCES EMPRESA (COD_EMPRESA)
	 );










