USE MINIERP_MULT;

--CRIAÇÃO TABELAS CARGOS
  CREATE TABLE CARGOS
    (
	 COD_EMPRESA     INT                 NOT NULL,
	 COD_CARGO       INT IDENTITY(1,1)   NOT NULL,
	 NOME_CARGO      VARCHAR(50),
	 CONSTRAINT PK_CARG1 PRIMARY KEY (COD_EMPRESA, COD_CARGO),
	 CONSTRAINT FK_CARG1 FOREIGN KEY (COD_EMPRESA)
	 REFERENCES EMPRESA (COD_EMPRESA)
	 );

--CRIAÇÃO TABELA FUNCIONARIO
--DROP	TABLE FUNCIONARIO
  CREATE TABLE FUNCIONARIO
    (
	 COD_EMPRESA    INT          NOT NULL,
	 MATRICULA      INT          NOT NULL,
	 COD_CC	        VARCHAR(4)   NOT NULL,
	 NOME           VARCHAR(50)  NOT NULL,
	 RG             VARCHAR(15)  NOT NULL,
	 CPF            VARCHAR(15)  NOT NULL,
	 ENDERECO       VARCHAR(50)  NOT NULL,
	 NUMERO         VARCHAR(10)  NOT NULL,
	 BAIRRO         VARCHAR(50)  NOT NULL,
	 COD_CIDADE     VARCHAR(7)   NOT NULL,
	 DATA_ADMISS    DATE         NOT NULL,
     DATA_DEMISS    DATE,
     DATE_NASC      DATE         NOT NULL,
	 TELEFONE       VARCHAR(15)  NOT NULL,
	 COD_CARGO      INT          NOT NULL,
	 CONSTRAINT FK_FUNC1 FOREIGN KEY (COD_EMPRESA, COD_CC)
	 REFERENCES CENTRO_CUSTO (COD_EMPRESA,COD_CC),
	 CONSTRAINT FK_FUNC2 FOREIGN KEY (COD_CIDADE)
	 REFERENCES CIDADES      (COD_CIDADE),
	 CONSTRAINT FK_FUNC3 FOREIGN KEY (COD_EMPRESA, COD_CARGO)
	 REFERENCES CARGOS       (COD_EMPRESA,COD_CARGO),
	 CONSTRAINT PK_FUNC1 PRIMARY KEY(COD_EMPRESA, MATRICULA)
	 );

--CRIAÇÃO TABELA SALARIO
--DROP TABLE SALARIO
--SELECT * FROM SALARIO 

  CREATE TABLE SALARIO
    (
	 COD_EMPRESA    INT            NOT NULL,
	 MATRICULA      INT            NOT NULL,
	 SALARIO        DECIMAL (10,2) NOT NULL,
	 CONSTRAINT FK_SAL2 FOREIGN KEY (COD_EMPRESA, MATRICULA)
	 REFERENCES FUNCIONARIO(COD_EMPRESA, MATRICULA),
	 CONSTRAINT PK_SAL1 PRIMARY KEY (COD_EMPRESA,MATRICULA)
	  );

--CRIAÇÃO TABLE FOLHA DE PAGTO
--DROP TABLE FOLHA_PAGTO
  CREATE TABLE FOLHA_PAGTO
    (
	 COD_EMPRESA  INT             NOT NULL,
	 MATRICULA    INT             NOT NULL, 
	 TIPO_PAGTO   CHAR(1)         NOT NULL, --(M-FOLHA, A-ADTO, F-FERIAS, D-13º, R-RESC),
	 TIPO         CHAR(1)         NOT NULL,--P=	PROVENTOS D=DESCONTO
	 EVENTO       VARCHAR(30)     NOT NULL,
	 MES_REF      VARCHAR(2)      NOT NULL,
	 ANO_REF      VARCHAR(4)      NOT NULL,
	 DATA_PAGTO   DATE            NOT NULL,
	 VALOR	      DECIMAL(10,2)   NOT NULL,
	 CONSTRAINT FK_FP1 FOREIGN KEY (COD_EMPRESA, MATRICULA)
	 REFERENCES FUNCIONARIO (COD_EMPRESA, MATRICULA)
	  );
  --CRIANDO INDEX
    CREATE INDEX IX1_FOLHA ON FOLHA_PAGTO(COD_EMPRESA, MATRICULA);

--SEGURANÇA
--CRIAÇÃO TABELA USUARIOS
  CREATE TABLE USUARIO
    (
	 COD_EMPRESA  INT           NOT NULL,
	 LOGIN        VARCHAR(30)   NOT NULL PRIMARY KEY,
	 MATRICULA    INT           NOT NULL,
	 SENHA        VARCHAR(32)   NOT NULL,
	 SITUACAO     CHAR(1)       NOT NULL, --A=ATIVO, B=BLOQUEADO
	 CONSTRAINT FK_US1 FOREIGN KEY (COD_EMPRESA, MATRICULA)
	 REFERENCES FUNCIONARIO(COD_EMPRESA,MATRICULA)
	 );

--FINANCEIRO
--CRIAÇÃO TABELA CONTAS A RECEBER
  CREATE TABLE CONTAS_RECEBER
  (
   COD_EMPRESA      INT               NOT NULL,
   ID_DOC           INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
   ID_CLIENTE       INT               NOT NULL,
   ID_DOC_ORIG      INT               NOT NULL, --ALTER CAMPO ID_DOC_ORIG PARA FK TABELA NOTA_FISCAL
   PARC             INT               NOT NULL,
   DATA_VENC        DATE              NOT NULL,
   DATA_PAGTO       DATE,
   VALOR            DECIMAL(10,2),
   CONSTRAINT FK_CR1 FOREIGN KEY(COD_EMPRESA, ID_CLIENTE)
   REFERENCES CLIENTES(COD_EMPRESA,ID_CLIENTE)
   );

--CRIAÇÃO TABELA CONTAS A PAGAR
--DROP TABLE CONTAS_PAGAR
  CREATE TABLE CONTAS_PAGAR
    (
	  COD_EMPRESA    INT               NOT NULL,
	  ID_DOC         INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	  ID_FORNEC      INT               NOT NULL,
      ID_DOC_ORIG    INT               NOT NULL, --ALTER CAMPO ID_DOC_ORIG PARA FK TABELA NOTA FISCAL
	  PARC           INT               NOT NULL,
	  DATA_VENC      DATE              NOT NULL,
	  DATA_PAGTO     DATE,
	  VALOR          DECIMAL(10,2),
	  CONSTRAINT FK_CP1 FOREIGN KEY (COD_EMPRESA, ID_FORNEC)
	  REFERENCES FORNECEDORES (COD_EMPRESA, ID_FORNEC)
	  );


--CRIAÇÃO TABELA CONDIÇÕES DE PAGAMENTO 
--DROP TABLE COND_PAGTO
  CREATE TABLE COND_PAGTO
    (
	 COD_PAGTO  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	 NOME_CP     VARCHAR(50)       NOT NULL,
     );
--CRIAÇÃO DE TABELAS DETALHES DE CONDIÇÃO DE PAGAMENTO COM PARCELA
  CREATE TABLE  COND_PAGTO_DET
    ( 
	 COD_PAGTO   INT           NOT NULL,
	 PARC        INT           NOT NULL,
	 DIAS        INT           NOT NULL,
	 PCT         DECIMAL(10,2) NOT NULL, --PERCENTUAL DA PARCELA
	 CONSTRAINT FK_CONDP1 FOREIGN KEY (COD_PAGTO)
	 REFERENCES COND_PAGTO (COD_PAGTO)
	  );

--COMERCIAL
--CRIAÇÃO TABELA PEDIDO DE VENDAS
  
  CREATE  TABLE  PED_VENDAS
    (
	  COD_EMPRESA     INT            NOT NULL,
	  NUM_PEDIDO      INT            NOT NULL,
	  ID_CLIENTE      INT            NOT NULL,
	  COD_PAGTO       INT            NOT NULL,
	  DATA_PEDIDO     DATE           NOT NULL,
	  DATA_ENTREGA    DATE           NOT NULL,
	  SITUACAO        NCHAR(1)       NOT NULL, --A=ABERTO, P=PLANEJADO, F=FINALIZADO
	  TOTAL_PED       DECIMAL(10,2),
	  CONSTRAINT FK_PV1 FOREIGN KEY (COD_EMPRESA, ID_CLIENTE)
	  REFERENCES CLIENTES(COD_EMPRESA, ID_CLIENTE),
	  CONSTRAINT FK_PV2 FOREIGN KEY (COD_PAGTO)
	  REFERENCES COND_PAGTO(COD_PAGTO),
	  CONSTRAINT PK_PV1 PRIMARY KEY (COD_EMPRESA, NUM_PEDIDO),
	  );

--CRIAÇÃO DA TABELA PEDIDO VENDAS ITENS
  CREATE TABLE PED_VENDAS_ITENS
   (
    COD_EMPRESA   INT             NOT NULL,
	NUM_PEDIDO    INT             NOT NULL,
	SEQ_MAT       INT             NOT NULL,
	COD_MAT       INT             NOT NULL,
	QTD           INT	          NOT NULL,
	VAL_UNIT      DECIMAL(10,2)   NOT NULL,
    CONSTRAINT FK_PVIT1 FOREIGN KEY (COD_EMPRESA, NUM_PEDIDO)
	REFERENCES PED_VENDAS(COD_EMPRESA, NUM_PEDIDO),
	CONSTRAINT PK_PVIT1 PRIMARY KEY (COD_EMPRESA, NUM_PEDIDO,SEQ_MAT)
	 );

--CRIAÇÃO TABELAS VENDEDORES
--DROP TABLE VENDEDORES
  CREATE TABLE VENDEDORES	
   (
    COD_EMPRESA   INT NOT NULL,
	MATRICULA     INT NOT NULL,
	CONSTRAINT FK_VEND1 FOREIGN KEY (COD_EMPRESA, MATRICULA)
	REFERENCES FUNCIONARIO (COD_EMPRESA, MATRICULA)
    );

--CRIAÇÃO TABELA GERENTES DE VENDAS
  CREATE TABLE GERENTES	
   (
    COD_EMPRESA  INT NOT NULL,
	MATRICULA    INT NOT NULL,
	CONSTRAINT FK_GER1 FOREIGN KEY (COD_EMPRESA, MATRICULA)
	REFERENCES FUNCIONARIO(COD_EMPRESA, MATRICULA)
	 );

--CANAL DE VENDAS RELACIONA GERENTE COM VENDEDOR
  CREATE TABLE CANAL_VENDAS_G_V
   (
    COD_EMPRESA        INT NOT NULL,
	MATRICULA_GER      INT NOT NULL,
	MATRICULA_VEND     INT,
	CONSTRAINT FK_CGV1 FOREIGN KEY (COD_EMPRESA, MATRICULA_GER)
	REFERENCES FUNCIONARIO(COD_EMPRESA, MATRICULA),
	CONSTRAINT FK_CGV2 FOREIGN KEY (COD_EMPRESA, MATRICULA_VEND)
	REFERENCES FUNCIONARIO(COD_EMPRESA, MATRICULA),
	CONSTRAINT PK_CGV1 PRIMARY KEY (COD_EMPRESA, MATRICULA_GER, MATRICULA_VEND)
	);

--CANAL DE VENDAS RELACIONA VENDEDOR COM CLIENTE 
--DROP TABLE CANAL_VENDAS_V_C
  CREATE TABLE CANAL_VENDAS_V_C
   (
    COD_EMPRESA        INT NOT NULL,
	MATRICULA_VEND     INT NOT NULL,
	ID_CLIENTE         INT NOT NULL,
	CONSTRAINT FK_CVC1 FOREIGN KEY (COD_EMPRESA, MATRICULA_VEND)
	REFERENCES FUNCIONARIO(COD_EMPRESA, MATRICULA),
	CONSTRAINT FK_CVC2 FOREIGN KEY (COD_EMPRESA, ID_CLIENTE)
	REFERENCES CLIENTES(COD_EMPRESA, ID_CLIENTE)
	);

--CRIAÇÃO DE TABELA PARA REGISTRA META DE VENDAS MES A MES/ANO
  CREATE TABLE META_VENDAS
   (
	COD_EMPRESA       INT             NOT NULL,
	MATRICULA_VEND    INT             NOT NULL,
	ANO               VARCHAR(4)      NOT NULL,
	MES               VARCHAR(2)      NOT NULL,
	VALOR             DECIMAL(10,2),
	CONSTRAINT FK_MV1 FOREIGN KEY (COD_EMPRESA, MATRICULA_VEND)
	REFERENCES FUNCIONARIO(COD_EMPRESA, MATRICULA)
	);

--FISCAL
--CRIAÇÃO DA TABELA DOS CODIGO DE OPERAÇÕES FISCAIS
--DROP TABLE CFOP
  CREATE TABLE CFOP
  (
   COD_CFOP   VARCHAR(5)     NOT NULL PRIMARY KEY,
   DESC_CFOP  VARCHAR(225)   NOT NULL
   );

--CRIAÇÃO DA TABELA NOTA_FISCAL
--DROP TABLE NOTA_FICAL
--DROP TABLE NOTA _FISCAL_ITENS
  CREATE TABLE NOTA_FISCAL
   (
    COD_EMPRESA       INT            NOT NULL,
	NUM_NF            INT            NOT NULL,
	TIP_NF            CHAR(1)        NOT NULL, --E=ENTRADA, S=SAIDA
	COD_CFOP          VARCHAR(5)     NOT NULL,
	ID_CLIFOR         INT            NOT NULL,
	COD_PAGTO         INT            NOT NULL,
	DATA_EMISSAO      DATETIME       NOT NULL,
	DATA_ENTREGA      DATE           NOT NULL,
	TOTAL_NF          DECIMAL(10,2),
	INTEGRADA_FIN     CHAR(1) DEFAULT('N'),
	INTEGRADA_SUP     CHAR(1) DEFAULT('N'),
	CONSTRAINT FK_NF1 FOREIGN KEY (COD_CFOP)
	REFERENCES CFOP(COD_CFOP),
	CONSTRAINT FK_NF2 FOREIGN KEY (COD_PAGTO)
	REFERENCES COND_PAGTO(COD_PAGTO),
	CONSTRAINT PK_NF1 PRIMARY KEY (COD_EMPRESA,NUM_NF)
	);

--CRIAÇÃO DA TABELA NOTA_FICAL_ITENS
  CREATE TABLE NOTA_FICAL_ITENS
  ( 
   COD_EMPRESA   INT            NOT NULL,
   NUM_NF        INT            NOT NULL,
   SEQ_MAT       INT            NOT NULL,
   COD_MAT       INT            NOT NULL,
   QTD           INT            NOT NULL,
   VAL_UNIT      DECIMAL(10,2)  NOT NULL,
   PED_ORIG      INT            NOT NULL,
   CONSTRAINT FK_NFIT1 FOREIGN KEY (COD_EMPRESA,NUM_NF)
   REFERENCES NOTA_FISCAL(COD_EMPRESA, NUM_NF),
   CONSTRAINT FK_NFIT2 FOREIGN KEY (COD_EMPRESA, COD_MAT)
   REFERENCES MATERIAL (COD_EMPRESA, COD_MAT)
   );

--CRIAÇÃO TABELAS PARAMETRO DE INSS
  CREATE TABLE PARAM_INSS
   (
    VIGENCIA_INI   DATE,
	VIGENCIA_FIM   DATE,
	VALOR_DE       DECIMAL(10,2)   NOT NULL,
	VALOR_ATE      DECIMAL(10,2)   NOT NULL,
	PCT            DECIMAL(10,2)   NOT NULL
	);

--CRIAÇÃO TABELAS PARAMETRO DO IRRF
  CREATE TABLE PARAM_IRRF
   (
    VIGENCIA_INI   DATE,
	VIGENCIA_FIM   DATE,
	VALOR_DE       DECIMAL(10,2)  NOT NULL,
	VALOR_ATE      DECIMAL(10,2) NOT NULL,
	PCT            DECIMAL(10,2) NOT NULL,
	VAL_ISENT      DECIMAL(10,2)
	);	

--CRIAÇÃO TABELAS AUDIT SALARIO
   CREATE TABLE AUDITORIA_SALARIO
    (
	 COD_EMPRESA        INT             NOT NULL,
	 MATRICULA          VARCHAR(30)     NOT NULL,
	 SAL_ANTES          DECIMAL(10,2)   NOT NULL,
	 SAL_DEPOIS         DECIMAL(10,2)   NOT NULL,
	 USUARIO            VARCHAR(20)     NOT NULL,
	 DATA_ATUALIZACAO   DATETIME        NOT NULL
	 );

--TABELAS DE PARAMETROS PARA AUTONUMERAÇÃO
  CREATE TABLE PARAMETROS
  (
   COD_EMPRESA   INT           NOT NULL,
   PARAM         VARCHAR(50)   NOT NULL,
   VALOR         INT           NOT NULL,
   CONSTRAINT FK_PARAM1 FOREIGN KEY (COD_EMPRESA)
   REFERENCES EMPRESA (COD_EMPRESA),
   CONSTRAINT PK_PARAM1 PRIMARY KEY (COD_EMPRESA,PARAM)
   );

--CREATE INDEX IX_PARAM1 ON PARAMETROS(COD_EMPRESA, PARAM);

--ADD CAMPO	LOGIN TABELA APONTAMENTOS CRIAÇÃOAPOS TABELA USUARIOS E FK
  ALTER TABLE APONTAMENTOS ADD LOGIN VARCHAR(30) NOT NULL;
--ADICIONAR CAMPO LOTE NA TABELA APONTAMENTOS
  ALTER TABLE APONTAMENTOS ADD LOTE VARCHAR(20) NOT NULL;

--ADD CAMPO LOGIN TABELA ESTOQUE_MOV CRIAÇÃO APOS TABELA USUARIO
  ALTER TABLE ESTOQUE_MOV ADD LOGIN VARCHAR(30) NOT NULL;



