--MINI ERP
--USE MASTER 
--DROP DATABASE MINIERP_MULT
--GO
  
  CREATE DATABASE MINIERP_MULT
  GO

  USE MINIERP_MULT;


--CADASTROS COMPLEMENTARES POR AREA
--CRIANDO TABELAS SEM DEPENDENCIAS/DEPENDENTES

--CREATE TABLE EMPRESA
  CREATE TABLE EMPRESA
  (COD_EMPRESA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
   NOME_EMPRESA VARCHAR(50),
   FANTASIA VARCHAR(20)
   );

--TABELA UNIDADE FEDERAL
--DROP TABLE UF
  CREATE TABLE UF
  (
     COD_UF VARCHAR(2) NOT NULL PRIMARY KEY,
	 NOME_UF VARCHAR(30) NOT NULL,
   );

--TABELAS CIDADES
  
	  CREATE TABLE CIDADES 
	  (
	   COD_CIDADE VARCHAR(7) NOT NULL PRIMARY KEY,
	   COD_UF VARCHAR(2) NOT NULL,
	   NOME_MUN VARCHAR(50) NOT NULL,
	   CONSTRAINT FK_CID1 FOREIGN KEY (COD_UF) REFERENCES UF(COD_UF)
	   );

--CRIANDO TABELAS CLIENTES
  CREATE TABLE CLIENTES
   (
    COD_EMPRESA   INT               NOT NULL,
	ID_CLIENTE    INT IDENTITY(1,1) NOT NULL,
	RAZAO_CLIENTE VARCHAR(100)      NOT NULL,
	FANTASIA      VARCHAR(15)       NOT NULL,
	ENDERECO      VARCHAR(50)       NOT NULL,
	NRO           VARCHAR(10)       NOT NULL,
	BAIRRO        VARCHAR(20)       NOT NULL, 
	COD_CIDADE    VARCHAR(7)        NOT NULL,
	CEP           VARCHAR(8),
	CNPJ_CPF      VARCHAR(15),
	TIPO_CLIENTE   NCHAR(1)   CONSTRAINT CK_TC1 CHECK (TIPO_CLIENTE IN ('F','J')),
	DATA_CADASTRO DATETIME          NOT NULL,
	COD_PAGTO     INT,
    CONSTRAINT PK_CLI1 PRIMARY KEY  (COD_EMPRESA,ID_CLIENTE),
    CONSTRAINT FK_CLI1 FOREIGN KEY  (COD_CIDADE)
    REFERENCES CIDADES (COD_CIDADE),
	CONSTRAINT FK_CLI2 FOREIGN KEY  (COD_EMPRESA)
    REFERENCES EMPRESA (COD_EMPRESA)
	 );

--CRIANDO TABELA FORNECEDORES
  CREATE TABLE FORNECEDORES
  (
    COD_EMPRESA	  INT	        NOT NULL,
	ID_FORNEC     INT IDENTITY  NOT NULL,
	RAZAO_FORNEC  VARCHAR(100)  NOT NULL,
	FANTASIA      VARCHAR(15)   NOT NULL,
	ENDERECO      VARCHAR(50)   NOT NULL,
	NRO           VARCHAR(10)   NOT NULL,
	BAIRRO        VARCHAR(20)   NOT NULL,
	COD_CIDADE    VARCHAR(7)    NOT NULL,
	CEP           VARCHAR(8),
	CNPJ_CPF      VARCHAR(15),
	TIPO_FORNEC   NCHAR(1)    CONSTRAINT CK_TF1 CHECK (TIPO_FORNEC IN ('F','J')),
	DATA_CADASTRO DATETIME      NOT NULL,
	COD_PAGTO     INT,
	CONSTRAINT PK_FORNEC1 PRIMARY KEY  (COD_EMPRESA,ID_FORNEC),
    CONSTRAINT FK_FORNEC1 FOREIGN KEY  (COD_CIDADE)
    REFERENCES CIDADES (COD_CIDADE),
	CONSTRAINT FK_FORNEC2 FOREIGN KEY  (COD_EMPRESA)
    REFERENCES EMPRESA (COD_EMPRESA)
    );

--VERIFICANDO 
  SELECT * FROM FORNECEDORES

--TABELAS TIPO DE MATERIAL	
  CREATE TABLE TIPO_MAT
   (
    COD_EMPRESA  INT          NOT NULL,
	COD_TIP_MAT  INT          NOT NULL,
	DESC_TIP_MAT VARCHAR(20)  NOT NULL,
	CONSTRAINT PK_TIP_M1 PRIMARY KEY (COD_EMPRESA, COD_TIP_MAT),
	CONSTRAINT FK_TIP_M1 FOREIGN KEY (COD_EMPRESA)
	REFERENCES EMPRESA (COD_EMPRESA)
     );

--CRIANDO TABELAS MATERIAL
  CREATE TABLE MATERIAL
   (
   COD_EMPRESA  INT            NOT NULL,
   COD_MAT      INT            NOT NULL,
   DESCRICAO    VARCHAR(50)    NOT NULL,
   PRECO_UNIT   DECIMAL(10,2)  NOT NULL,
   COD_TIP_MAT  INT            NOT NULL,
   ID_FORNEC    INT,
   CONSTRAINT PK_MAT1 PRIMARY KEY  (COD_EMPRESA,COD_MAT),
   CONSTRAINT FK_MAT1 FOREIGN KEY  (COD_EMPRESA,COD_TIP_MAT)
   REFERENCES TIPO_MAT (COD_EMPRESA,COD_TIP_MAT)
   /*CONSTRAINT FK_MAT2 FOREIGN KEY (COD_EMPRESA,ID_FORNEC)
     REFERENCES FORNECEDORES (COD_EMPRESA,ID_FORNEC)
	 */  
   --ALTER TABLE MARETIAL DROP CONSTRAINT FK_MAT2 
	);

--CRIANDO INDEX
  CREATE INDEX IX_MAT ON MATERIAL (COD_EMPRESA,COD_TIP_MAT)


--PRODUÇAO
--DROP TABLE ORDEM_PROD
  CREATE TABLE ORDEM_PROD
    (
	 COD_EMPRESA     INT                NOT NULL,
	 ID_ORDEM        INT IDENTITY(1,1)  NOT NULL,
	 COD_MAT_PROD    INT                NOT NULL,
	 QTD_PLAN        DECIMAL(10,2)      NOT NULL,
	 QTD_PROD        DECIMAL(10,2)      NOT NULL,
	 DATE_INI        DATE,
	 DATE_FIM        DATE,
	 SITUACAO        CHAR(1)  --A(ABERTA), P(PLANEJADA), F(FECHADA)
	 CONSTRAINT PK_OP1 PRIMARY KEY (COD_EMPRESA,ID_ORDEM),
	 CONSTRAINT FK_OP1 FOREIGN KEY (COD_EMPRESA, COD_MAT_PROD)
	 REFERENCES	MATERIAL (COD_EMPRESA, COD_MAT),
	 );







